import React, { useEffect, useState } from 'react'
import Head from 'next/head'

//  Step 1: Find the file corresponding to the slug
//  Step 2: Populate them inside the page 

const Slug = (props) => {
  function createMarkup(content) {
    return {__html: content};
  }
  const [blog, setblog] = useState(props.myBlog);
  
    
  return (
    <div>
        <Head>
        <title>{blog && blog.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='text-center'>
    <div className='text-3xl font-bold'>{blog && blog.title}</div>
    <hr className='mt-5 mb-9'/>
    {blog && <div className='mx-22 lg:mx-32' dangerouslySetInnerHTML={createMarkup(blog.content)} />}
    </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  const {slug} = context.query;

  let data = await fetch(`http://localhost:3000/api/getblog?slug=${slug}`);
  let myBlog = await data.json();
      
  return {
    props: { myBlog }, // will be passed to the page component as props
  }
}



export default Slug