import React from 'react'
import {useRouter} from 'next/router'
import Head from 'next/head'

//  Step 1: Find the file corresponding to the slug
//  Step 2: Populate them inside the page 

const Slug = () => {
    const router = useRouter();
    const {slug} = router.query;
  return (
    <div>
        <Head>
        <title>{slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='text-center'>
    <div className='text-3xl font-bold'>{slug}</div>
    <hr className='mt-5 mb-9'/>
    <p className='mx-32'>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores ipsum nesciunt exercitationem non, adipisci dolores omnis veritatis corporis cupiditate libero deleniti incidunt rem iste, cum expedita! Debitis neque amet architecto perferendis magnam dignissimos sed deleniti magni nesciunt earum laboriosam illo explicabo minus sequi veniam, modi blanditiis corporis accusantium. Similique quo, voluptatum reprehenderit recusandae dolores voluptatibus nihil commodi, iure ab libero error obcaecati dolorum nam perspiciatis velit tempora, modi suscipit magni veritatis quis aperiam ducimus sit fuga cum. Tempore quos unde eum laboriosam ad beatae quasi ex, laudantium reiciendis veritatis animi, facere error, rerum tempora dolorem!
    </p>
    </div>
    </div>
  )
}

export default Slug