import React, { useEffect, useState } from 'react'
import {useRouter} from 'next/router'
import Head from 'next/head'

//  Step 1: Find the file corresponding to the slug
//  Step 2: Populate them inside the page 

const Slug = () => {
  const [blog, setblog] = useState([]);
  const router = useRouter();
  useEffect(() => {
    if (!router.isReady) return;
    const {slug} = router.query;
    fetch(`http://localhost:3000/api/getblog?slug=${slug}`).then((a)=>{
    return a.json(); })
    .then((parsed)=>{
   setblog(parsed)
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [router.isReady])
  
    
  return (
    <div>
        <Head>
        <title>{blog && blog.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='text-center'>
    <div className='text-3xl font-bold'>{blog && blog.title}</div>
    <hr className='mt-5 mb-9'/>
    <p className='mx-22 lg:mx-32'>
     {blog && blog.content}
    </p>
    </div>
    </div>
  )
}

export default Slug