import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import Head from 'next/head'

// Step 1: Collect all data from blogdata directory
// Step 2: iterate them and display them

const blog = (props) => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [blogs, setblogs] = useState(props.allBlogs)
  // eslint-disable-next-line react-hooks/rules-of-hooks
  // useEffect(() => {
  // fetch('http://localhost:3000/api/blogs').then((a)=>{
  //   return a.json(); })
  //   .then((parsed)=>{
  //  setblogs(parsed)
  // })
  // }, [])

  return (
    <div>
      <Head>
        <title>Blogs | Newschaser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font overflow-hidden mx-24">
        <div className="container px-5 py-24 mx-auto">
          <div className="-my-8 divide-y-2 divide-gray-100">
            {blogs.map((blogitem) => {
              return <div className="py-8 flex flex-wrap md:flex-nowrap" key={blogitem.slug}>

                <div className="md:flex-grow">
                  <h2 className="text-2xl font-medium text-gray-900 title-font mb-2">{blogitem.title}</h2>
                  <p className="leading-relaxed">{blogitem.content.substr(0, 160)}...</p>
                  <div className="md:w-64 md:mb-0 mb-9 flex-shrink-0 flex flex-col">
                    <span className="font-semibold title-font text-gray-700">{blogitem.category}</span>
                    <span className="mt-1 text-gray-500 text-sm">{blogitem.date}</span>
                  </div>
                  <Link href={`/blogpost/${blogitem.slug}`}><a className="text-indigo-500 inline-flex items-center mt-4">Learn More
                    <svg className="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M5 12h14"></path>
                      <path d="M12 5l7 7-7 7"></path>
                    </svg>
                  </a></Link>
                </div>
              </div>
            })}
          </div>
        </div>
      </section>
    </div>
  )
}

export async function getServerSideProps(context) {

  let data = await fetch('http://localhost:3000/api/blogs');
  let allBlogs = await data.json();
 
  return {
    props: { allBlogs }, // will be passed to the page component as props
  }
}


export default blog